### ISSUE TITLE
Crashing when i started game

### ISSUE THREAD

**Issue by egemencadana** [TomB-134/MinimalMenu#21]
Crash log is here
[crash-2021-05-19_21.30.58-client.txt](https://github.com/TomB-134/MinimalMenu/files/6510955/crash-2021-05-19_21.30.58-client.txt)

**Comment by TomB-134** [comment]
With that many mods installed it's hard to identify which is causing the issue, my mod is not designed or intended to work in the way that you're using it (with what looks like a large amount of mods). My suggestion is to remove mods one by one until your client works again to find the conflict. Otherwise finding an alternative to my mod that works well with other mods is probably best. Cheers, -Tom
